name = "GregTech Odyssey"
version = "0.5.6-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9684da8a35c620791a9c96b52832d3c1ea32da7d2672f1a816c5e36ab3a7bca0"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
