name = "GregTech Odyssey"
version = "0.5.4-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9474cb2da23605adb6ab4a8efeeeee80fdb1d71a3c17910fde6ff2a2c7a1c968"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
