name = "GregTech Odyssey"
version = "0.5.6-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd1e3a9c045464f3bd4d0ea1f9d07dd89ead5015d790f964d3abccfdf3ff774c"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
