# Prevent cheating
selfRestraint: false

# Enabled, no mining required
enablePrimitiveVoidOre: false

# Check for conflicts between recipes
recipeCheck: false

# Reduce resource usage for the MultiBlock page (Reduce memory usage, improve startup speed, only on the client side)
disableMultiBlockPage: false

# Remove unnecessary loading
fastMultiBlockPage: true

# The interval increases gradually when the machine cannot find a recipe; this is the maximum interval.
recipeMaxCheckInterval: 80

# Ore product multiplier
oreMultiplier: 4

spacetimePip: 2147483647

eioFluidRate: 16

breakBlocksBlackList:
  - ae2:cable_bus

enableAnimalsAreAfraidToEatTheirMeat: true

enableAnimalsAreAfraidToEatTheirMeatRange: 12

