
[serverConfig]

permissionSystem = "ftb_ranks"
primaryPartySystem = "ftb_teams"
playerConfigurablePlayerConfigOptions = []

[serverConfig.parties]
enabled = false

[serverConfig.claims]
maxPlayerClaimForceloads = 10000
maxPlayerClaims = 10000
maxClaimDistance = 100