
#DoesPotatoTick?
["Living Entities Tick Settings"]
	#If you disable this, entities will not stop ticking when they're far from you, this mod may be useless for you too
	OptimizeEntitiesTicking = true
	#If you don't want an entity to be affected by the optimization, you can write its registry name down here.
	EntitiesWhitelist = ["minecraft:ender_dragon", "minecraft:ghast", "minecraft:wither", "minecraft:player"]
	#If you don't want entities of a mod to be affected by the optimization, you can write its modid down here
	EntitiesModIDWhiteList = []
	#Similar to entity whitelist, but only take effect in raid.
	RaidEntitiesWhiteList = ["minecraft:witch", "minecraft:vex"]
	#Similar to entity modID whitelist, but only take effect in raid
	RaidEntitiesModIDWhiteList = []
	#Leave this empty for applying to all the dimensions
	#Entities in these dimensions will be affected by the optimization
	DimensionWhitelist = []
	#If this is enabled, dead entities will always tick
	IgnoreDeadEntities = false
	#With this turned on, all the raider will always tick if the world has raids
	TickRaidersIfRaid = true
	#If this is enabled, hostile entities will always tick
	IgnoreHostileEntities = false
	#If this is enabled, projectiles will always tick
	IgnoreProjectiles = true
	#If this is enabled, optimization will only take effect on living entities
	OnlyLivingOptimizable = false
	#Range: > 1
	LivingEntitiesMaxHorizontalTickDistanceInChunks = 4
	#Range: > 1
	LivingEntitiesMaxVerticalTickDistanceInChunks = 2

["Item Entities Tick Settings"]
	#Slow down item entities' ticking speed
	#Note this does impact rendering continuity, so this optimization is disabled by default
	OptimizeItemMovement = false
	#If you don't want to let a specific item entity in the world to be effected by the optimization, you can write its registry name down here.
	#Require 'OptimizeItemMovement' to be true
	ItemWhiteList = []
	#If this is enabled, item entities will always tick
	IgnoreItemEntities = true

[Misc]
	SendWarningMessageWhenPlayerLogIn = false
	#If enabled, entities ticking in other threads will not be affected
	OnlyWorksOnServerThread = true

[Client]
	#If the tick of an entity is skipped by this mod, stop its client rendering so that players won't get it stuck in their worlds.
	StopRenderingSkippedEntities = true

