name: "Localization"
on:
  push:
    paths:
      - 'config/ftbquests/quests/**'
  pull_request:
    paths:
      - 'config/ftbquests/quests/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install python deps
        run: pip install -r .github/localization/requirements.txt

      - name: Generate Translate Keys
        run: python .github/localization/ftbquest_localization.py

      - name: Update Quest Localization
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Quest Localization
