name: "Refresh"
on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      old_commit:
        description: 'Provide an old commit SHA for custom incremental sync'
        required: true
        default: ''
  
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取全部历史

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install python deps
        run: pip install -r .github/localization/requirements.txt

      - name: Generate Translate Keys (Push)
        if: github.event_name == 'push'
        run: python .github/localization/ftbquest_localization.py push "${{ github.event.before }}"

      - name: Generate Translate Keys (Pull Request) # 用于 PR 检测是否已执行过本地化脚本
        if: github.event_name == 'pull_request'
        run: python .github/localization/ftbquest_localization.py pr ""

      - name: Generate Translate Keys (Manual)
        if: github.event_name == 'workflow_dispatch'
        run: python .github/localization/ftbquest_localization.py push "${{ github.event.inputs.old_commit }}"

      - name: Generate Traditional Translate Keys
        run: python .github/localization/chinese_converter.py

      - name: Make packwiz executable
        run: chmod +x .github/packwiz

      - name: Packwiz Refresh
        run: .github/packwiz refresh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Quest Localization & Refresh
