name: "Refresh"
on:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make packwiz executable
        run: chmod +x .github/packwiz

      - name: Packwiz Refresh
        run: .github/packwiz refresh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Packwiz Refresh
